language: node_js
node_js:
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-beego' ]; then cd .. && eval "mv $currentfolder generator-beego" && cd generator-beego; fi

